
const REQUEST_SUCCESS = '00';
const REQUEST_FAILED = '99';

const REQUSET_FILE_SAVE_SUCCESS = '80';
const REQUEST_FILE_SAVE_FAILED = '81';

const AUTH_STATUS_LOGIN = 'LOGIN';
const AUTH_STATUS_LOGOUT = 'LOGOUT';

